server:
  port: 8081          # WebSocket 전용 서버 포트

spring:
  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis

api:
  server:
    base-url: "http://localhost:8080" # 기존 API 서버 주소
